### ISSUE TITLE
can I put this up on a site?

### ISSUE THREAD

**Issue by samuelfullerthomas** [karmakettle/allamo#1]
Heya! Long time no see!

I think this is a pretty cool / useful thing - would you mind if I threw it up on a site - called something like allamo.club?

Whatcha up to these days?

**Comment by karmakettle** [comment]
Hey there, it's good to hear from you! I'm pretty excited that you're finding this useful and don't mind if you wanna host it somewhere. The only caveat is that the site shouldn't have a lot of traffic (be limited to personal use) because the api isn't public (I'd go that route if it were!)... Hope the Drafthouse (ALL HAIL) isn't negatively affected (I don't think it would be) and doesn't mind this project existing 🤞

Also, the movie list only includes the Austin area atm. If you're still in the same place, you'll want to change the market segment of the api call from `0000` to `2100`. 

Feel free to email/message me if you have any questions about it or are passing through!
